#!/bin/bash
# This is the cloud-init script used to install the build machine rpm
#
# Use this path as your user-data in the EC2 instance create:
# https://raw.githubusercontent.com/karlredgate/build-server/master/cloud-init
#

BUILDREPO=http://github.com/karlredgate/build-server/releases/download

yum --enablerepo=epel --enablerepo=epel-testing \
    install --quiet -y $BUILDREPO/v1.0/build-server-1.0-3.bfac140.m302135404.noarch.rpm

# vim:autoindent expandtab sw=4
